[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
line_length = 120

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E402,E501"
]
