[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_first_party = ["sentinelhub", "eolearn", "eogrow", "hiector"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
line_length = 120

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E402,E501,F841",
]

[tool.nbqa.exclude]
flake8 = "super-resolution-fastai/"


[tool.ruff.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "our-packages",
    "first-party",
    "local-folder",
]
sections = { our-packages = ["sentinelhub", "eolearn"] }
