name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64

      - name: Prepare pre-commit validators
        run: |
          pip install pre-commit
          pre-commit install

      - name: Check code compliance with pre-commit validators
        run: pre-commit run --all-files
